import type { MetadataRoute } from 'next';

const BASE_URL = 'https://www.farmsense.kr';

/** 공개 페이지 경로 (동적 라우트 제외) */
const staticPaths = [
    '',
    '/about',
    '/agriculture-data-platform',
    '/ai-diagnosis-why',
    '/crops',
    '/crops/apple',
    '/crops/grape',
    '/crops/melon',
    '/crops/other',
    '/crops/strawberry',
    '/data-intelligence',
    '/delete-account',
    '/developers/api-guide',
    '/education',
    '/education/advanced',
    '/education/beginner',
    '/education/environment',
    '/export-intelligence',
    '/export/country-requirements',
    '/export/data-documents',
    '/export/gap-certification',
    '/export/roadmap',
    '/faq',
    '/grape-info',
    '/grape-intelligence',
    '/intelligent-logic',
    '/intelligent-logic/environmental-control',
    '/intelligent-logic/fertilizer-application',
    '/intelligent-logic/grape-cultivation',
    '/intelligent-logic/irrigation-water',
    '/intelligent-logic/pesticide-spray',
    '/intelligent-logic/yield-prediction',
    '/partners',
    '/platform',
    '/platform/benefits',
    '/platform/case-studies',
    '/platform/how-it-works',
    '/privacy-policy',
    '/refund-policy',
    '/services',
    '/solutions',
    '/solutions/climate',
    '/solutions/dss',
    '/solutions/grow',
    '/solutions/protect',
    '/solutions/residue',
    '/solutions/trace',
    '/solutions/ventilation',
    '/solutions/yield',
    '/strawberry',
    '/support',
    '/support/ai-assistant',
    '/support/board',
    '/technology',
    '/technology/ai-diagnosis',
    '/technology/blockchain',
    '/technology/camera-necessity',
    '/technology/data-strategy',
    '/technology/diagnosis-guide',
    '/technology/docs',
    '/technology/logic',
    '/technology/logic/disease',
    '/technology/logic/fertilizer',
    '/technology/logic/grape',
    '/technology/logic/water',
    '/technology/logic/yield',
    '/technology/pmi-dss',
    '/technology/rag-system',
    '/terms',
    '/verified-farms',
];

export default function sitemap(): MetadataRoute.Sitemap {
    const now = new Date();
    return staticPaths.map((path) => ({
        url: `${BASE_URL}${path || '/'}`,
        lastModified: now,
        changeFrequency: (path === '' || path.startsWith('/technology') || path.startsWith('/intelligent-logic') || path.startsWith('/solutions')) ? 'weekly' as const : 'monthly' as const,
        priority: path === '' ? 1 : (path.startsWith('/technology') || path.startsWith('/intelligent-logic') || path.startsWith('/solutions') || path.startsWith('/crops') || path.startsWith('/platform')) ? 0.9 : 0.7,
    }));
}
